name: 📦 Reusable Aggregate Workflow (Downstream)

on:
  workflow_call:
    inputs:
      artifacts:
        required: true
        type: string

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download All Artifacts
        run: |
          echo "Downloading artifacts..."
          for artifact_name in ${{ inputs.artifacts }}; do
            echo "Downloading $artifact_name"
            gh run download-artifact "$artifact_name" --dir ./artifacts
          done

      - name: Display All OS Info
        run: |
          echo "========== Aggregated OS Information =========="
          for file in $(find ./artifacts -type f -name "*.txt"); do
            echo "--- $file ---"
            cat "$file"
            echo
          done
