name: 📦 Reusable Aggregate Workflow (Downstream)

on:
  workflow_call:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display all OS info
        run: |
          echo "========== Aggregated OS Information =========="
          for file in $(find ./artifacts -type f -name "*.txt"); do
            echo "--- $file ---"
            cat "$file"
            echo
          done
